version: '3.1'

services:
  node-bot:
    build: ./bot
    image: telegram-forwarder-node-bot
    environment:
      AGENT_PORT: 3000
      AGENT_HOSTNAME: python-agent
      TG_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      DB_HOST: postgres-db
      NTBA_FIX_319: 1
    depends_on:
      - postgres-db

  python-agent:
    build: './agent'
    image: 'telegram-forwarder-python-agent'
    depends_on:
      - postgres-db
    environment:
      API_PORT: 3000
      TG_API_ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      TG_HASH_ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      DB_HOST: postgres-db
    ports:
      - '3000:3000'

  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
